name: Build OpenWrt 25.12 EFI K6.18

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Env
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev swig

      - name: Clone OpenWrt
        run: git clone --depth 1 https://github.com/openwrt/openwrt -b openwrt-25.12 openwrt

      - name: Update Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Apply Custom Configuration
        run: |
          chmod +x diy-part2.sh
          ./diy-part2.sh
          mv .config openwrt/.config
          cd openwrt
          make defconfig

      - name: Compile
        run: |
          cd openwrt
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Organize Files
        run: |
          mkdir -p publish
          cp openwrt/bin/targets/x86/64/*-squashfs-combined-efi.img.gz publish/

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_EFI_K6.18
          path: publish/
